print("Nivel facil")
print("\n")
print("1.")
print("Martín Del Río")
print("18 años")
print("2. -> Canción favorita: ´After Hours - The Weeknd´")
print("\n")
print("Nivel medio")
print("\n")
print("Ej 3. -> Hallo -.-")
print("\n")
print("Ej 4.")
print("\n")
print("5!")
print("4!")
print("3!")
print("2!")
print("1!")
print("\n")
print("Nivel dificil(saltar por ahora)")
print("\n")